import type { SetCategory, Tier } from "@/types/items";

export const SETS: { name: SetCategory; tier: Tier }[] = [
    { name: "Angelic Raiment", tier: "Normal" },
    { name: "Arcanna's Tricks", tier: "Normal" },
    { name: "Arctic Gear", tier: "Normal" },
    { name: "Berserker's Arsenal", tier: "Normal" },
    { name: "Cathan's Traps", tier: "Normal" },
    { name: "Civerb's Vestments", tier: "Normal" },
    { name: "Cleglaw's Brace", tier: "Normal" },
    { name: "Death's Disguise", tier: "Normal" },
    { name: "Hsarus' Defense", tier: "Normal" },
    { name: "Infernal Tools", tier: "Normal" },
    { name: "Iratha's Finery", tier: "Normal" },
    { name: "Isenhart's Armory", tier: "Normal" },
    { name: "Milabrega's Regalia", tier: "Normal" },
    { name: "Sigon's Complete Steel", tier: "Normal" },
    { name: "Tancred's Battlegear", tier: "Normal" },
    { name: "Vidala's Rig", tier: "Normal" },
    { name: "Cow King's Leathers", tier: "Exceptional" },
    { name: "Heaven's Brethren", tier: "Exceptional" },
    { name: "Hwanin's Majesty", tier: "Exceptional" },
    { name: "Naj's Ancient Vestige", tier: "Exceptional" },
    { name: "Orphan's Call", tier: "Exceptional" },
    { name: "Sander's Folly", tier: "Exceptional" },
    { name: "Sazabi's Grand Tribute", tier: "Exceptional" },
    { name: "The Disciple", tier: "Exceptional" },
    { name: "Aldur's Watchtower", tier: "Elite" },
    { name: "Bul-Kathos' Children", tier: "Elite" },
    { name: "Griswold's Legacy", tier: "Elite" },
    { name: "Immortal King", tier: "Elite" },
    { name: "M'avina's Battle Hymn", tier: "Elite" },
    { name: "Natalya's Odium", tier: "Elite" },
    { name: "Tal Rasha's Wrappings", tier: "Elite" },
    { name: "Trang-Oul's Avatar", tier: "Elite" },
];
